/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectBdatabase.views;

import ProjectBdatabase.databaseUtil.Connector;
import ProjectBdatabase.models.Locatie;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jelmer
 */
public class LocatieAanpassen extends javax.swing.JFrame {

    /**
     * Creates new form LocatieToevoegen
     */
    private LocatieOpties locatieOpties;
    private Locatie currentlocatie;

    public LocatieAanpassen(LocatieOpties locatieOpties, Locatie current) {
        initComponents();
        this.locatieOpties = locatieOpties;
        this.currentlocatie = current;

        tfNaam.setText(this.currentlocatie.naam());
        tfMaxaantal.setText(String.valueOf(this.currentlocatie.maxAantalDeelnemers()));
        tfHuur.setText(String.valueOf(this.currentlocatie.huur()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNaam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfMaxaantal = new javax.swing.JTextField();
        tfHuur = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Locatie aanpassen");

        jLabel1.setText("Locatienaam:");

        jLabel2.setText("Max aantal deelnemers:");

        jLabel3.setText("Huur:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfMaxaantal)
                                .addComponent(tfHuur, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfMaxaantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfHuur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int aantalValidFields = 0;

            String naam = this.tfNaam.getText();
            String maxaantal = this.tfMaxaantal.getText();
            String huur = this.tfHuur.getText();

            if (CheckInput.checkInput(naam) == 0) {
                tfNaam.setBackground(Color.RED);
            } else {
                tfNaam.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }

            if (CheckInput.checkNummer(maxaantal) == 0) {
                tfMaxaantal.setBackground(Color.RED);
            } else {
                tfMaxaantal.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }

            if (CheckInput.checkDouble(huur) == 0) {
                tfHuur.setBackground(Color.RED);
            } else {
                tfHuur.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }

            if (aantalValidFields == 3) {
                try {
                    Connection conn = Connector.getConnection();

                    String prepStatWijzigLocatie = "UPDATE locatie SET naam=?,max_aantal_deelnemers=?,huur = ? WHERE huisnummer=? AND postcode=?";

                    PreparedStatement prepStat = conn.prepareStatement(prepStatWijzigLocatie);

                    prepStat.setString(1, naam);
                    prepStat.setInt(2, Integer.parseInt(maxaantal));
                    prepStat.setDouble(3, Double.parseDouble(huur));
                    prepStat.setString(4, currentlocatie.huisnummer());
                    prepStat.setString(5, currentlocatie.postcode());

                    prepStat.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Locatie is gewijzigd ");
                    this.locatieOpties.Vullijst();
                    this.dispose();
                } catch (SQLException exc) {
                    JOptionPane.showMessageDialog(this, "Locatie niet gewijzigd: " + exc.toString());
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfHuur;
    private javax.swing.JTextField tfMaxaantal;
    private javax.swing.JTextField tfNaam;
    // End of variables declaration//GEN-END:variables
}
