/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectBdatabase.views;

import ProjectBdatabase.models.Speler;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import ProjectBdatabase.databaseUtil.Connector;
import java.awt.Color;

/**
 *
 * @author Ruben
 */
public class SpelerAanpassen extends javax.swing.JFrame {

    private SpelerOpties spelerOpties;
    private Speler currentspeler;

    public SpelerAanpassen(SpelerOpties spelerOpties, Speler current) {
        this.spelerOpties = spelerOpties;
        initComponents();
        this.currentspeler = current;

        lbSpelerID.setText(String.valueOf(this.currentspeler.s_code()));
        tfNaam.setText(this.currentspeler.naam());
        tfHuisnummer.setText(this.currentspeler.huisnummer());
        tfPostcode.setText(this.currentspeler.postcode());
        tfWoonplaats.setText(this.currentspeler.woonplaats());
        tfTelefoonnummer.setText(this.currentspeler.telefoonnummer());
        tfEmail.setText(this.currentspeler.email());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTelefoonnummer = new javax.swing.JTextField();
        tfWoonplaats = new javax.swing.JTextField();
        tfPostcode = new javax.swing.JTextField();
        tfHuisnummer = new javax.swing.JTextField();
        tfNaam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbSpelerID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speler aanpassen");

        jLabel3.setText("Naam:");

        jLabel4.setText("Postcode:");

        jLabel5.setText("Huisnummer:");

        jLabel6.setText("Woonplaats:");

        tfTelefoonnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefoonnummerActionPerformed(evt);
            }
        });

        jButton1.setText("Annuleren");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefoonnummer:");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Email:");

        jLabel1.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSpelerID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelefoonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSpelerID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfTelefoonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int aantalValidFields = 0;

            // TODO add your handling code here:
            String naam = this.tfNaam.getText();
            String huisnummer = this.tfHuisnummer.getText();
            String postcode = this.tfPostcode.getText();
            String woonplaats = this.tfWoonplaats.getText();
            String telefoon = this.tfTelefoonnummer.getText();
            String email = this.tfEmail.getText();

            if (CheckInput.checkLetters(naam) == 0) {
                tfNaam.setBackground(Color.RED);
            } else {
                tfNaam.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }
            if (CheckInput.checkHuisnummer(huisnummer) == 0) {
                tfHuisnummer.setBackground(Color.RED);
            } else {
                tfHuisnummer.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }
            if (CheckInput.checkPostcode(postcode) == 0) {
                tfPostcode.setBackground(Color.RED);
            } else {
                tfPostcode.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }
            if (CheckInput.checkLetters(woonplaats) == 0) {
                tfWoonplaats.setBackground(Color.RED);
            } else {
                tfWoonplaats.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }
            if (CheckInput.checkTelefoonnummer(telefoon) == 0) {
                tfTelefoonnummer.setBackground(Color.RED);
            } else {
                tfTelefoonnummer.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }
            if (CheckInput.checkEmail(email) == 0) {
                tfEmail.setBackground(Color.RED);
            } else {
                tfEmail.setBackground(Color.WHITE);
                aantalValidFields = aantalValidFields + 1;
            }

            if (aantalValidFields == 6) {
                try {
                    Connection conn = Connector.getConnection();

                    String prepStatWijzigKlant = "UPDATE Speler SET naam=?, huisnummer=?,postcode=?,woonplaats=?,telefoonnummer=?, email=? WHERE s_code=?";

                    PreparedStatement prepStat = conn.prepareStatement(prepStatWijzigKlant);

                    prepStat.setString(1, naam);
                    prepStat.setString(2, huisnummer);
                    prepStat.setString(3, postcode);
                    prepStat.setString(4, woonplaats);
                    prepStat.setString(5, telefoon);
                    prepStat.setString(6, email);
                    prepStat.setInt(7, currentspeler.s_code());

                    prepStat.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Speler is gewijzigd ");
                    this.spelerOpties.Vullijst();
                    this.dispose();
                } catch (SQLException exc) {
                    JOptionPane.showMessageDialog(this, "Speler niet gewijzigd: " + exc.toString());
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfTelefoonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefoonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefoonnummerActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbSpelerID;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHuisnummer;
    private javax.swing.JTextField tfNaam;
    private javax.swing.JTextField tfPostcode;
    private javax.swing.JTextField tfTelefoonnummer;
    private javax.swing.JTextField tfWoonplaats;
    // End of variables declaration//GEN-END:variables
}
