/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectBdatabase.views;

import ProjectBdatabase.databaseUtil.Connector;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruben
 */
public class SpelerToevoegen extends javax.swing.JFrame {

    private SpelerOpties spelerOpties;

    public SpelerToevoegen(SpelerOpties spelerOpties) {
        this.spelerOpties = spelerOpties;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfTelefoon = new javax.swing.JTextField();
        tfWoonplaats = new javax.swing.JTextField();
        tfPostcode = new javax.swing.JTextField();
        tfHuisnummer = new javax.swing.JTextField();
        tfNaam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speler toevoegen");

        jLabel3.setText("Naam:");

        jLabel4.setText("Huisnummer:");

        jLabel5.setText("Postcode:");

        jLabel6.setText("Woonplaats:");

        jLabel7.setText("Telefoonnummer:");

        tfHuisnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHuisnummerActionPerformed(evt);
            }
        });

        tfNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNaamActionPerformed(evt);
            }
        });

        jButton1.setText("Annuleren");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmail)
                            .addComponent(tfWoonplaats)
                            .addComponent(tfPostcode)
                            .addComponent(tfHuisnummer)
                            .addComponent(tfNaam)
                            .addComponent(tfTelefoon, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHuisnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfWoonplaats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTelefoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHuisnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHuisnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHuisnummerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int aantalValidFields = 0;

        int klantNummer = 0;
        String naam = this.tfNaam.getText();
        String huisnummer = this.tfHuisnummer.getText();
        String Postcode = this.tfPostcode.getText();
        String Woonplaats = this.tfWoonplaats.getText();
        String Telefoon = this.tfTelefoon.getText();
        String Email = this.tfEmail.getText();

        if (CheckInput.checkLetters(naam) == 0) {
            tfNaam.setBackground(Color.RED);
        } else {
            tfNaam.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }
        if (CheckInput.checkHuisnummer(huisnummer) == 0) {
            tfHuisnummer.setBackground(Color.RED);
        } else {
            tfHuisnummer.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }
        if (CheckInput.checkPostcode(Postcode) == 0) {
            tfPostcode.setBackground(Color.RED);
        } else {
            tfPostcode.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }
        if (CheckInput.checkLetters(Woonplaats) == 0) {
            tfWoonplaats.setBackground(Color.RED);
        } else {
            tfWoonplaats.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }
        if (CheckInput.checkTelefoonnummer(Telefoon) == 0) {
            tfTelefoon.setBackground(Color.RED);
        } else {
            tfTelefoon.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }
        if (CheckInput.checkEmail(Email) == 0) {
            tfEmail.setBackground(Color.RED);
        } else {
            tfEmail.setBackground(Color.WHITE);
            aantalValidFields = aantalValidFields + 1;
        }

        if (aantalValidFields == 6) {
            try {
                Connection conn = Connector.getConnection();
                Statement stat = conn.createStatement();

                String prepStatInsertKlant = "INSERT INTO speler (s_code, naam, huisnummer,postcode,woonplaats,telefoonnummer,email,rating,totaalgewonnengeld) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?,1000,0)";
                PreparedStatement prepStat = conn.prepareStatement(prepStatInsertKlant);

                prepStat.setInt(1, klantNummer);
                prepStat.setString(2, naam);
                prepStat.setString(3, huisnummer);
                prepStat.setString(4, Postcode);
                prepStat.setString(5, Woonplaats);
                prepStat.setString(6, Telefoon);
                prepStat.setString(7, Email);

                prepStat.executeUpdate();

                stat.close();

                JOptionPane.showMessageDialog(this, "Klant opgeslagen in de database");
                this.spelerOpties.Vullijst();
                this.dispose();
            } catch (SQLException exc) {
                JOptionPane.showMessageDialog(this, "Klant niet opgeslagen in de database" + exc.toString());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNaamActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHuisnummer;
    private javax.swing.JTextField tfNaam;
    private javax.swing.JTextField tfPostcode;
    private javax.swing.JTextField tfTelefoon;
    private javax.swing.JTextField tfWoonplaats;
    // End of variables declaration//GEN-END:variables
}
